### ISSUE TITLE
Pick and Place File for PCB Assembly

### ISSUE THREAD

**Issue by OpenSourceIronman** [eclipse/kuksa.hardware#8]
I'm ordering PCBs for assembly at https://jlcpcb.com/order and can't seem to find the pick and place file that I assumed would be in EDA directory somewhere near https://github.com/TesCustoms/TesMufflerDongle/tree/main/EDA/PiOBD_CM4_MultiBoard_V1.1/TopBoard/Project%20Outputs%20for%20TopBoard

Linked below is a sample CPL file that JCL PCB provided:
https://www.icloud.com/iclouddrive/050_UZ1zaG_tQxW3B6V0IZN7w#JLCSMT_Sample_CPL1

**Comment by eriksven** [comment]
Hi @OpenSourceIronman , the team which worked on the hardware dongle is currently on their Christmas and New Years break. So I am afraid that we will not have a good answer to your question until next week. Sorry about that.

**Comment by SebastianSchildt** [comment]
What @eriksven said. I will try to reach out to our hw gurus and see what we can do. Might take some days though. What I can say, the reason, we did not notice this particular information missing is, that for our first production  run our "Pick & place machines" where human-based...

**Comment by OpenSourceIronman** [comment]
Thanks guys! I will also probably hand solder paste and then drag solder the first two PCBs myself 🤓 

But then plan to make ~100 units in May 2023, 400 more in Aug 2023, and then final 1500 more in Oct 2023. 

https://docs.google.com/presentation/d/1vmfBdLqMhj65gBI4U_X0QDvzo5LgiAgdK-cK7LWeqZQ/edit

**Comment by SebastianSchildt** [comment]
If you really manage to make them (sourcing is a bit difficult for some of the components), I am pretty sure you could also have customers outside your specific project.

We saw quite a bit interest around the "Software Defined Vehicle" Open Source community, to use this for various projects, but so far we did not manage pre-financing a complete batch.

So if you do manage to move forward with this design, or something based on it, be sure to ping us, or advertise here https://sdv.eclipse.org 

At least it might help you getting some additional volume 🤓 

We updated the manufacturing files to include Pick&Place, fresh Gerber export and some other documentation improvements. We should(tm) not have missed any vital files and PCB should not have  been changed, but just to be sure, previous master is tagged here: https://github.com/eclipse/kuksa.hardware/tree/hardware2_v11

**Comment by OpenSourceIronman** [comment]
I really appreciate the update. I will double check everything and get back to the team in 7 to 10 days.
